apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-event-generator
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: falco-event-generator
        image: sysdig/falco-event-generator:latest